backend:
  name: github
  repo: William-LP/William-LP.github.io
  branch: main
media_folder: static/img
public_folder: /img
collections:
  - name: "author"
    label: "Author Information"
    files:
      - label: "Author"
        name: "author"
        file: "data/en/author.yaml"
        fields:
          - label: "Name"
            name: "name"
            widget: "string"
          - label: "Nickname"
            name: "nickname"
            widget: "string"
          - label: "Contact Information"
            name: "contactInfo"
            widget: "object"
            fields:
              - label: "Email"
                name: "email"
                widget: "string"
              - label: "Phone"
                name: "phone"
                widget: "string"
              - label: "GitHub"
                name: "github"
                widget: "string"
              - label: "LinkedIn"
                name: "linkedin"
                widget: "string"
          - label: "Summary"
            name: "summary"
            widget: "list"
            field:
              label: "Item"
              name: "item"
              widget: "string"
  - name: "about"
    label: "About Section"
    files:
      - label: "About Page"
        name: "about_page"
        file: "data/en/sections/about.yaml"
        fields:
          - label: "Designation"
            name: "designation"
            widget: "string"

          - label: "Company"
            name: "company"
            widget: "object"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "URL"
                name: "url"
                widget: "string"

          - label: "Summary"
            name: "summary"
            widget: "text"

          - label: "Social Links"
            name: "socialLinks"
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "Icon"
                name: "icon"
                widget: "string"
              - label: "URL"
                name: "url"
                widget: "string"
              - label: "Rel"
                name: "rel"
                widget: "string"
                required: false

          - label: "Resource Links"
            name: "resourceLinks"
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "URL"
                name: "url"
                widget: "string"

          - label: "Badges"
            name: "badges"
            widget: "list"
            fields:
              - label: "Type"
                name: "type"
                widget: "string"
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "URL"
                name: "url"
                widget: "string"
              - label: "Badge"
                name: "badge"
                widget: "image"
                media_folder: "static/images/badges"
                public_folder: "/images/badges"
              - label: "Percentage"
                name: "percentage"
                widget: "number"
                required: false
              - label: "Color"
                name: "color"
                widget: "string"
                required: false

  - name: "skills"
    label: "Skills Section"
    files:
      - label: "Skills"
        name: "skills_page"
        file: "data/en/sections/skills.yaml"
        fields:
          - label: "Skills"
            name: "skills"
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "Logo"
                name: "logo"
                widget: "image"
                media_folder: "static/images/sections/skills"
                public_folder: "/images/sections/skills"
              - label: "Summary"
                name: "summary"
                widget: "text"
              - label: "URL"
                name: "url"
                widget: "string"
                required: false

  - name: "experiences"
    label: "Experiences Section"
    files:
      - label: "Experiences"
        name: "experiences_page"
        file: "data/en/sections/experiences.yaml"
        fields:
          - label: "Experiences"
            name: "experiences"
            widget: "list"
            fields:
              - label: "Company"
                name: "company"
                widget: "object"
                fields:
                  - label: "Company Name"
                    name: "name"
                    widget: "string"
                  - label: "Company URL"
                    name: "url"
                    widget: "string"
                  - label: "Location"
                    name: "location"
                    widget: "string"
                  - label: "Logo"
                    name: "logo"
                    widget: "image"
                    media_folder: "static/images/sections/experiences"
                    public_folder: "/images/sections/experiences"
                  - label: "Dark Theme Logo"
                    name: "darkLogo"
                    widget: "image"
                    required: false
                    media_folder: "static/images/sections/experiences"
                    public_folder: "/images/sections/experiences"
                  - label: "Overview"
                    name: "overview"
                    widget: "text"

              - label: "Positions"
                name: "positions"
                widget: "list"
                fields:
                  - label: "Designation"
                    name: "designation"
                    widget: "string"
                  - label: "Start Date"
                    name: "start"
                    widget: "string"
                    hint: "Provide a start date (e.g., 'Nov 2019')."
                  - label: "End Date"
                    name: "end"
                    widget: "string"
                    required: false
                    hint: "Leave blank if currently working here. 'Present' will be shown."
                  - label: "Responsibilities"
                    name: "responsibilities"
                    widget: "list"
                    field:
                      label: "Responsibility"
                      name: "responsibility"
                      widget: "string"

  - name: "education"
    label: "Education Section"
    files:
      - label: "Education"
        name: "education_page"
        file: "data/en/sections/education.yaml" # Path to the education YAML file
        fields:
          - label: "Degrees"
            name: "degrees"
            widget: "list"
            fields:
              - label: "Degree Name"
                name: "name"
                widget: "string"
              - label: "Icon"
                name: "icon"
                widget: "string"
              - label: "Timeframe"
                name: "timeframe"
                widget: "string"
              - label: "Institution"
                name: "institution"
                widget: "object"
                fields:
                  - label: "Institution Name"
                    name: "name"
                    widget: "string"
                  - label: "Institution URL"
                    name: "url"
                    widget: "string"
                    required: false
                  - label: "Logo"
                    name: "logo"
                    widget: "image"
                    media_folder: "static/images/sections/education"
                    public_folder: "/images/sections/education"
                  - label: "Dark Theme Logo"
                    name: "darkLogo"
                    widget: "image"
                    required: false
                    media_folder: "static/images/sections/education"
                    public_folder: "/images/sections/education"

              - label: "Grade"
                name: "grade"
                widget: "object"
                required: false
                fields:
                  - label: "Scale"
                    name: "scale"
                    widget: "string"
                  - label: "Achieved"
                    name: "achieved"
                    widget: "number"
                  - label: "Out Of"
                    name: "outOf"
                    widget: "number"

              - label: "Publications"
                name: "publications"
                widget: "list"
                required: false
                fields:
                  - label: "Title"
                    name: "title"
                    widget: "string"
                  - label: "URL"
                    name: "url"
                    widget: "string"

              - label: "Taken Courses"
                name: "takenCourses"
                widget: "object"
                required: false
                fields:
                  - label: "Show Grades"
                    name: "showGrades"
                    widget: "boolean"
                  - label: "Collapse After"
                    name: "collapseAfter"
                    widget: "number"
                  - label: "Courses"
                    name: "courses"
                    widget: "list"
                    fields:
                      - label: "Course Name"
                        name: "name"
                        widget: "string"
                      - label: "Achieved Grade"
                        name: "achieved"
                        widget: "number"
                      - label: "Out Of"
                        name: "outOf"
                        widget: "number"

              - label: "Extracurricular Activities"
                name: "extracurricularActivities"
                widget: "list"
                required: false
                field:
                  label: "Activity"
                  name: "activity"
                  widget: "string"

              - label: "Custom Sections"
                name: "customSections"
                widget: "list"
                required: false
                fields:
                  - label: "Section Name"
                    name: "name"
                    widget: "string"
                  - label: "Content"
                    name: "content"
                    widget: "text"

  - name: "projects"
    label: "Projects Section"
    files:
      - label: "Projects"
        name: "projects_page"
        file: "data/en/sections/projects.yaml"
        fields:
          - label: "Filter Buttons"
            name: "buttons"
            widget: "list"
            fields:
              - label: "Button Name"
                name: "name"
                widget: "string"
              - label: "Filter"
                name: "filter"
                widget: "string"

          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - label: "Project Name"
                name: "name"
                widget: "string"
              - label: "Project Logo"
                name: "logo"
                widget: "image"
                required: false
                media_folder: "static/images/sections/projects"
                public_folder: "/images/sections/projects"
              - label: "Role"
                name: "role"
                widget: "string"
              - label: "Timeline"
                name: "timeline"
                widget: "string"
              - label: "Repository URL"
                name: "repo"
                widget: "string"
                required: false
              - label: "External URL"
                name: "url"
                widget: "string"
                required: false
              - label: "Summary"
                name: "summary"
                widget: "text"
              - label: "Tags"
                name: "tags"
                widget: "list"
                field:
                  label: "Tag"
                  name: "tag"
                  widget: "string"
